FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .

# Set environment variables
ENV REACT_APP_API_URL=http://localhost:5000
ENV WDS_SOCKET_PORT=0

# Expose port 3000
EXPOSE 3000

# Start the app in development mode
CMD ["npm", "start"]
